import * as React from 'react';
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from '@/components/ui/card';
import { Badge } from '@/components/ui/badge';
import { AlertTriangle, ShieldCheck, Info, CheckCircle2, Factory } from 'lucide-react';
import { RiskReport } from '@/types';
import { cn } from '@/lib/utils';

interface RiskAnalysisProps {
  report: RiskReport | null;
  loading?: boolean;
  manufacturerName?: string;
}

export function RiskAnalysis({ report, loading, manufacturerName }: RiskAnalysisProps) {
  if (loading) {
    return (
      <Card className="border-none shadow-xl shadow-black/5 bg-white animate-pulse">
        <div className="h-64 flex items-center justify-center">
          <div className="flex flex-col items-center gap-4">
            <div className="w-12 h-12 border-4 border-black border-t-transparent rounded-full animate-spin" />
            <p className="text-gray-500 font-medium">Analyzing supply chain vectors...</p>
          </div>
        </div>
      </Card>
    );
  }

  if (!report) {
    return (
      <Card className="border-none shadow-xl shadow-black/5 bg-white">
        <div className="p-12 text-center">
          <div className="w-16 h-16 bg-gray-100 rounded-full flex items-center justify-center mx-auto mb-4">
            <AlertTriangle className="w-8 h-8 text-gray-400" />
          </div>
          <h3 className="text-lg font-bold text-gray-900 mb-2">
            {manufacturerName ? "No Analysis Performed" : "No Analysis Selected"}
          </h3>
          <p className="text-gray-500 max-w-sm mx-auto">
            {manufacturerName 
              ? `There are no historical risk assessments for ${manufacturerName}. Click "Start New Analysis" to initiate.`
              : "Select a technology provider from the list above to view their latest supply chain risk assessment."
            }
          </p>
        </div>
      </Card>
    );
  }

  const getRiskColor = (score: number) => {
    if (score < 30) return 'bg-green-100 text-green-700 border-green-200';
    if (score < 60) return 'bg-yellow-100 text-yellow-700 border-yellow-200';
    return 'bg-red-100 text-red-700 border-red-200';
  };

  return (
    <div className="space-y-6">
      <Card className="border-none shadow-xl shadow-black/5 bg-white overflow-hidden">
        <div className={cn(
          "h-2 w-full",
          report.riskScore < 30 ? "bg-green-500" : report.riskScore < 60 ? "bg-yellow-500" : "bg-red-500"
        )} />
        <CardHeader className="flex flex-row items-center justify-between">
          <div>
            <div className="flex items-center gap-2 mb-1">
              <Factory className="w-4 h-4 text-gray-400" />
              <span className="text-xs font-bold text-gray-500 uppercase tracking-wider">{manufacturerName || 'Unknown Manufacturer'}</span>
            </div>
            <CardTitle className="text-2xl font-bold">Risk Assessment Report</CardTitle>
            <CardDescription>Generated by Sentinel AI Engine</CardDescription>
          </div>
          <div className="text-right">
            <div className="text-4xl font-black text-gray-900">{report.riskScore}</div>
            <div className="text-xs font-bold text-gray-500 uppercase tracking-widest">Risk Index</div>
          </div>
        </CardHeader>
        <CardContent className="space-y-8">
          <div className="p-6 bg-gray-50 rounded-2xl border border-gray-100">
            <h4 className="font-bold text-gray-900 mb-2 flex items-center gap-2">
              <Info className="w-4 h-4" />
              Executive Summary
            </h4>
            <p className="text-gray-700 leading-relaxed">{report.summary}</p>
          </div>

          <div className="grid grid-cols-1 md:grid-cols-2 gap-8">
            <div className="space-y-4">
              <h4 className="font-bold text-gray-900 flex items-center gap-2">
                <AlertTriangle className="w-4 h-4 text-red-500" />
                Key Risk Factors
              </h4>
              <ul className="space-y-3">
                {report.keyRisks.map((risk, i) => (
                  <li key={i} className="flex items-start gap-3 p-3 bg-red-50/50 rounded-xl border border-red-100/50">
                    <div className="w-1.5 h-1.5 rounded-full bg-red-500 mt-2 shrink-0" />
                    <span className="text-sm text-gray-800">{risk}</span>
                  </li>
                ))}
              </ul>
            </div>

            <div className="space-y-4">
              <h4 className="font-bold text-gray-900 flex items-center gap-2">
                <ShieldCheck className="w-4 h-4 text-green-500" />
                Mitigation Strategies
              </h4>
              <ul className="space-y-3">
                {report.mitigationStrategies.map((strategy, i) => (
                  <li key={i} className="flex items-start gap-3 p-3 bg-green-50/50 rounded-xl border border-green-100/50">
                    <CheckCircle2 className="w-4 h-4 text-green-600 shrink-0" />
                    <span className="text-sm text-gray-800">{strategy}</span>
                  </li>
                ))}
              </ul>
            </div>
          </div>

          {report.threatActorLinks && report.threatActorLinks.length > 0 && (
            <div className="space-y-4">
              <h4 className="font-bold text-gray-900 flex items-center gap-2">
                <AlertTriangle className="w-4 h-4 text-orange-500" />
                Threat Intelligence Links
              </h4>
              <div className="flex flex-wrap gap-2">
                {report.threatActorLinks.map((actor, i) => (
                  <Badge key={i} variant="outline" className="bg-orange-50 text-orange-700 border-orange-200 rounded-xl px-4 py-1.5 font-bold">
                    {actor}
                  </Badge>
                ))}
              </div>
            </div>
          )}

          <div className="pt-6 border-t border-gray-100 flex items-center justify-between text-xs text-gray-400 font-mono">
            <span>ASSESSMENT ID: {report.id}</span>
            <span>TIMESTAMP: {new Date(report.assessedAt).toISOString()}</span>
          </div>
        </CardContent>
      </Card>
    </div>
  );
}
